max_width = 110
ideal_width = 80
fn_call_width = 60
struct_lit_width = 30
tab_spaces = 2
fn_brace_style = "PreferSameLine"
item_brace_style = "PreferSameLine"
fn_single_line = true
where_indent = "Visual"
where_layout = "Mixed"
chain_base_indent = "Visual"
chain_indent = "Visual"
reorder_imports = true
single_line_if_else = true
take_source_hints = false
wrap_comments = true
match_block_trailing_comma = true
closure_block_indent_threshold = 1
